### ISSUE TITLE
Cannot read property 'sha1' of undefined

### ISSUE THREAD

**Issue by almorak** [WalletConnect/react-native-simple-crypto#12]
"react": "16.6.3",
"react-native": "0.58.5",
"react-native-sha512": "^1.0.2",

It shows the Warning:
TypeError: Cannot read property 'sha1' of undefined

my code:
static async encrypt_pw(_password){
     let sha512_pw = await RNSimpleCrypto.SHA.sha1(_password);
     return sha512_pw;
}

when I logged the RNSimpleCrypto:
{
     AES: {encrypt: ƒ, decrypt: ƒ}
     HMAC: {hmac256: ƒ}
     PBKDF2: {hash: ƒ}
     RSA: undefined
     SHA: undefined
     utils: {randomBytes: ƒ, convertArrayBufferToUtf8: ƒ, convertUtf8ToArrayBuffer: ƒ, convertArrayBufferToBase64: ƒ, convertBase64ToArrayBuffer: ƒ, …}
}

**Comment by ghbutton** [comment]
is this iOS or Android? Please try with the latest version

**Comment by ghbutton** [comment]
Going to close, please reopen if there is still an issue
