### ISSUE TITLE
PBKDF2.hash should support ArrayBuffers

### ISSUE THREAD

**Issue by majorhayes** [WalletConnect/react-native-simple-crypto#19]
The project I'm on has a requirement for PBKDF2 hashing to accept an ArrayBuffer.  Since I added support for this already to the SHA functions, I'll be making a PR shortly to implement this following a similar pattern to how SHA was implemented (base64 for arraybuffers).

**Comment by ghbutton** [comment]
https://github.com/ghbutton/react-native-simple-crypto/pull/20

**Comment by ghbutton** [comment]
Thanks for writing this code
