### ISSUE TITLE
Add AES-256-CBC Support [iOS / Objective C] 

### ISSUE THREAD

**Issue by pedrouid** [WalletConnect/react-native-simple-crypto#2]
Currently the only supported encryption/decryption algorithm is AES-128-CBC.

The API for the AES module is the following currently:
```javascript
- AES
  - encrypt(text: ArrayBuffer, key: ArrayBuffer, iv: ArrayBuffer)
  - decrypt(cipherText: ArrayBuffer, key: ArrayBuffer, iv: ArrayBuffer)
```

The goal is to expand this API to include both AES-128-CBC and AES-256-CBC and expose the following API:
```javascript
- AES
  - aes128cbc
    - encrypt(text: ArrayBuffer, key: ArrayBuffer, iv: ArrayBuffer)
    - decrypt(cipherText: ArrayBuffer, key: ArrayBuffer, iv: ArrayBuffer)
  - aes256cbc
    - encrypt(text: ArrayBuffer, key: ArrayBuffer, iv: ArrayBuffer)
    - decrypt(cipherText: ArrayBuffer, key: ArrayBuffer, iv: ArrayBuffer)
```

For iOS, the file that includes the Common Crypto cipher is in Objective-C:
https://github.com/WalletConnect/react-native-simple-crypto/blob/master/ios/RCTCrypto/lib/Aes.m

**Acceptance Criteria:**
- It should match the AES-256-CBC spec
- It should match the targeted API
- It should avoid adding more dependencies

**Comment by ghbutton** [comment]
I think this should work now, it is just different key sizes
