### ISSUE TITLE
How can I decrypt AES encryption on NodeJS using CryptoJS?

### ISSUE THREAD

**Issue by bychung** [WalletConnect/react-native-simple-crypto#24]
After encrypted some data with AES, I sent to server and decrypt using crypto-js module on NodeJS.
But cannot be decrypted and just shows an empty string.

Below is the code on client using react-native-simple-crypto : 
```
import RNSimpleCrypto from 'react-native-simple-crypto';

encrypt(text: string, key: ArrayBuffer, iv: ArrayBuffer) {
 const encrypted = await RNSimpleCrypto.AES.encrypt(text, key, iv)
 return RNSimpleCrypto.utils.convertArrayBufferToHex(encrypted);
}
// After this, send encrypted result to server with key and iv, converted to hex string.
```

And below is the code on server using crypto-js : 
```
import CryptoJS from 'crypto-js';

decrypt(cipher: string, key: string, iv: string) {
  const cipherWA = CryptoJS.enc.Hex.parse(cipher); // convert hex string to WordArray
  const keyWA = CryptoJS.enc.Hex.parse(key);
  const ivWA = CryptoJS.enc.Hex.parse(iv);
  const decrypted = CryptoJS.AES.decrypt(cipherWA, keyWA, {
    iv: ivWA,
    mode: CryptoJS.mode.CBC,
  });
  return decrypted.toString();
}
```

Does the above two modules use different AES algorithm? I think it's not possible, but doubt it.

**Comment by bychung** [comment]
Found solution : AES decrypt function of crypto-js only accept ciphertext as Base64.

**Comment by ghbutton** [comment]
We will consider adding support for ArrayBuffer like many of the other algorithms
