### ISSUE TITLE
Add AES-256-CBC Support [Android / Java] 

### ISSUE THREAD

**Issue by pedrouid** [WalletConnect/react-native-simple-crypto#3]
Currently the only supported encryption/decryption algorithm is AES-128-CBC.

The API for the AES module is the following currently:
```javascript
- AES
  - encrypt(text: ArrayBuffer, key: ArrayBuffer, iv: ArrayBuffer)
  - decrypt(cipherText: ArrayBuffer, key: ArrayBuffer, iv: ArrayBuffer)
```

The goal is to expand this API to include both AES-128-CBC and AES-256-CBC and expose the following API:
```javascript
- AES
  - aes128cbc
    - encrypt(text: ArrayBuffer, key: ArrayBuffer, iv: ArrayBuffer)
    - decrypt(cipherText: ArrayBuffer, key: ArrayBuffer, iv: ArrayBuffer)
  - aes256cbc
    - encrypt(text: ArrayBuffer, key: ArrayBuffer, iv: ArrayBuffer)
    - decrypt(cipherText: ArrayBuffer, key: ArrayBuffer, iv: ArrayBuffer)
```

For Android, the file that includes the Java Extensions Crypto cipher is in Java:
https://github.com/WalletConnect/react-native-simple-crypto/blob/master/android/src/main/java/org/walletconnect/crypto/RCTAes.java

**Acceptance Criteria:**
- It should match the AES-256-CBC spec
- It should match the targeted API
- It should avoid adding more dependencies

**Comment by JohanObrink** [comment]
I ran some tests and if I understand it correctly this already works. The algorithm is the same as the block size is the same. The difference is the key length. I tried running encrypt/decrypt on iOS and Android with 256bit key length and got the same result as when running AES256CBC in node.

**Comment by ghbutton** [comment]
I agree with above, will close unless this is still an issue
