### ISSUE TITLE
[Request] Add Support for Native Keychain Access

### ISSUE THREAD

**Issue by Faolain** [WalletConnect/react-native-simple-crypto#30]
Similar to this library https://github.com/amitaymolko/react-native-rsa-native which "instead of directly accessing the private key, the private key is stored in the underlying operating system's keychain (see documentation for iOS and for Android) using a tag which the app can use to access it. Methods then take this tag instead of the private key." 

Relevant files for reference

**Android:** https://github.com/amitaymolko/react-native-rsa-native/blob/90286f26179fe849d3a0ca9290d8a74a74ac8867/android/src/main/java/com/RNRSA/RNRSAKeychainModule.java
**iOS:**  https://github.com/amitaymolko/react-native-rsa-native/blob/90286f26179fe849d3a0ca9290d8a74a74ac8867/ios/RNRSAKeychain.swift

Motivation: This library works extremely well and is missing just the addition of adding native key functionality.

**Comment by ghbutton** [comment]
I will take a look but I can you just store the private key after generating it using this library?

**Comment by ghbutton** [comment]
I dont think we will support this
