### ISSUE TITLE
How to update hmac256

### ISSUE THREAD

**Issue by joan17cast** [WalletConnect/react-native-simple-crypto#36]
Hello,

I need to replicate this code with your package. But i don't undestand how to do an update.

``` javascript
const buildSign = (data, config) => {
  return crypto.createHmac('sha256', config.API_SECRET).update(data).digest('hex');
};
```
Can you help me? 😄
For now i have this:

``` javascript
async function buildSign(data, config) {
    const keyHmac = await RNSimpleCrypto.utils.randomBytes(32);
    const signatureArrayBuffer = await RNSimpleCrypto.HMAC.hmac256(config.API_SECRET, keyHmac);
    console.log("HMAC signature", toHex(signatureArrayBuffer));
    return toHex(signatureArrayBuffer)
    
    //return crypto.createHmac('sha256', config.API_SECRET).update(data).digest('hex');
  };
```

Thanks you so much!

Sorry for my english 😋

**Comment by ghbutton** [comment]
What does `config.API_SECRET` look like? Is it a string or an array buffer?
What do you mean update data?

**Comment by joan17cast** [comment]
`config.API_SECRET` is an string. 

`data` is a timestamp looks like this = `1615576059289`

Its my first time using HMAC so im a bit lost. But i think i understand how this works in general. The `config.API_SECRET` is mix with the `data` to generate the HMAC signature.

Maybe i'm missing something and i need to do a previous step to mix before.

PD: I have tried without passing the `data` field and i have generated the HMAC signature, but the API has rejected my signature.

**Comment by ghbutton** [comment]
I think what you are trying to do is use the data as the hmac key, so I would bet it is something like `const keyHmac = data`. You may need to convert the integer into a string, not sure.

**Comment by joan17cast** [comment]
I try like this before, `int` and `string ` 

```javascript
async function buildSign(data, config) {
  try {
    const keyHmac =  data.toString()
    const signatureArrayBuffer = await RNSimpleCrypto.HMAC.hmac256( config.API_SECRET, keyHmac);
    console.log('HMAC signature', toHex(signatureArrayBuffer));
    return toHex(signatureArrayBuffer);

  } catch (error) {
    console.log('Error: ' + error.message);
  }
  //return crypto.createHmac('sha256', config.API_SECRET).update(data).digest('hex');
}
```

But both give the same error: `Invalid typed array length: 1615742072292`

**Comment by ghbutton** [comment]
Ok, sorry it is confusing I may update the documentation, both arguments are expected to be an array buffer.
This is the ruby that I used as the gold standard:
```
require 'openssl'

key = '1615576059289'
data = 'foo'
digest = OpenSSL::Digest.new('sha256')
 OpenSSL::HMAC.hexdigest(digest, key, data)
=> "16650890f158c8367e23ecfbb80314687de13fe916344b5abebdf3f85943fe9d"
```

And here is the javascript you can use:
```
const key = 1615576059289;
const keyBuffer = RNSimpleCrypto.utils.convertUtf8ToArrayBuffer(`${key}`);
const data = RNSimpleCrypto.utils.convertUtf8ToArrayBuffer("foo");
const signatureArrayBuffer = await RNSimpleCrypto.HMAC.hmac256(data, keyBuffer);
console.log("HMAC signature", toHex(signatureArrayBuffer));
```

**Comment by joan17cast** [comment]
My new code:
``` Javascript
async function buildSign(timestamp, key) {
  try {
    const keyBuffer = RNSimpleCrypto.utils.convertUtf8ToArrayBuffer(key);
    const data = RNSimpleCrypto.utils.convertUtf8ToArrayBuffer(timestamp.toString());
    const signatureArrayBuffer = await RNSimpleCrypto.HMAC.hmac256( data, keyBuffer);
    console.log('HMAC signature', toHex(signatureArrayBuffer));
    return toHex(signatureArrayBuffer);

  } catch (error) {
    console.log('Error: ' + error.message);
  }
  //return crypto.createHmac('sha256', config.API_SECRET).update(data).digest('hex');
} 
```
This makes the HMAC "works".
![image](https://user-images.githubusercontent.com/29452333/111350684-a9f1d200-8682-11eb-889a-c29c7758e6d8.png)

 But the API still give me an error from signature: 
![image](https://user-images.githubusercontent.com/29452333/111350965-f3dab800-8682-11eb-8353-e06a58330548.png)

I try it to exchange between `data` and `keyBuffer` and the `timestamp` between `init` and `string` , but with the same results.

I have tested the API on postman an it works perfect with the same initial keys. (With different timestamps). 

So I'm a bit lost on what I'm doing wrong 😔

**Comment by ghbutton** [comment]
This is definitely outside the library but I can try to be helpful. If it works with postman then you know a good input and output value? Can you replicate the outputs in the code giving the same inputs?

**Comment by joan17cast** [comment]
I found the error, thanks for the idea it was helpful. In the end was my fault tbh the API documentation is a bit difficult to follow because it disperse in different web pages.

But finaly it works. 🎉

Thank you so much for your time! @ghbutton you did a great job with this package, it helps a lot!
