### ISSUE TITLE
xcode build error in 12.5

### ISSUE THREAD

**Issue by brijpatel6080** [WalletConnect/react-native-simple-crypto#38]
Type of expression is ambiguous without more context
![119299309-4c7a9280-bc7c-11eb-9af7-441f5b75c1d7](https://user-images.githubusercontent.com/31682945/119605534-985d4100-be0e-11eb-9eee-311f801b5592.png)

**Comment by jim0020** [comment]
+1

**Comment by ghbutton** [comment]
Will try to reproduce

**Comment by jim0020** [comment]
> Will try to reproduce

Any luck with this?

**Comment by ghbutton** [comment]
I am seeing a different compile error, working on it now. Sorry things have been busy

**Comment by ghbutton** [comment]
I was able to install the new xcode but didn't get any app crash

**Comment by ghbutton** [comment]
This is the repo I used for testing: https://github.com/ghbutton/react-native-simple-crypto-test-2

**Comment by longb1997** [comment]
+1

**Comment by ghbutton** [comment]
Can anyone help me figure out how our setups are different? If you test with that test app do you get errors? Are you all getting the same build error?

**Comment by ghbutton** [comment]
<img width="994" alt="Screen Shot 2021-07-06 at 20 58 46" src="https://user-images.githubusercontent.com/757998/124698120-fb75d500-de9c-11eb-8044-5f5c400e28d8.png">

**Comment by longb1997** [comment]
I just realized that we are using the same fork from 'Rocket Chat/react-native-simple-crypto' 
Maybe...
btw, thanks for your support @ghbutton

**Comment by ghbutton** [comment]
What does that mean? What is the Rocket Chat fork?

**Comment by longb1997** [comment]
https://github.com/RocketChat/react-native-simple-crypto

**Comment by ghbutton** [comment]
Ahh yes, it seems like it is only that fork which has this problem. I dont have any knowledge of that code

**Comment by ghbutton** [comment]
Going to close out this issue unless there is something else
