### ISSUE TITLE
Task :react-native-simple-crypto:compileDebugJavaWithJavac 

### ISSUE THREAD

**Issue by rsimbu89** [WalletConnect/react-native-simple-crypto#8]
Hi ,
Getting below error while try to react-native run-android, 
But in iOS app working fine, Please help me to resolve this

```
/app path/projectname/node_modules/react-native-simple-crypto/android/src/main/java/org/walletconnect/crypto/RCTCryptoPackage.java:22: error: cannot find symbol
                new RandomBytesModule(reactContext)
                    ^
  symbol:   class RandomBytesModule
  location: class RCTCryptoPackage
/app path/projectname/node_modules/react-native-simple-crypto/android/src/main/java/org/walletconnect/crypto/RCTCryptoPackage.java:16: error: cannot find symbol
        return Arrays.<NativeModule>asList(
               ^
  symbol:   variable Arrays
  location: class RCTCryptoPackage
app path/projectname/node_modules/react-native-simple-crypto/android/src/main/java/org/walletconnect/crypto/RCTCryptoPackage.java:28: error: cannot find symbol
        return Arrays.<ViewManager>asList();
               ^
  symbol:   variable Arrays
  location: class RCTCryptoPackage
Note: app path/projectname/node_modules/react-native-simple-crypto/android/src/main/java/org/walletconnect/crypto/RSA.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors

FAILURE: Build failed with an exception.
```

**Comment by pedrouid** [comment]
Hey man, I haven't really looked into this repo in a while. I was trying to find alternatives to the combo with `react-native-crypto` and `rn-nodeify` but there really isn't any good ones. 

Check if you have run `react-native link` correctly. Otherwise you might need to manually link the Android native dependencies. Sorry I couldn't be more useful, I'm just not maintaining this library right now

**Comment by Foskas** [comment]
@rsimbu89 Have you found a solution ? I'm having the same issue.

**Comment by ghost** [comment]
Same Problem!

**Comment by pedrouid** [comment]
Hey guys, this library is **no longer maintained**. If you would like to fork this library and make a PR, I'm happy to merge it and publish to NPM. 

Alternatively you could also look at the original library this repository forked from:
[trackforce/react-native-crypto](https://github.com/trackforce/react-native-crypto)

Feel free to @ me to review any PRs

**Comment by tuur155** [comment]
I am having the same problem. Did anyone solve it already?

**Comment by ghbutton** [comment]
I think this is fixed, please test with the latest version

**Comment by ghbutton** [comment]
Going to close, please reopen if there is still an issue
